---
# Task file for myvhost


- name: install httpd
  yum:
    name: httpd
    state: latest

- name: Start and enable httpd service
  service:
    name: httpd
    state: restarted
    enabled: true

- name: deliver html content
  copy:
    src: html/
    dest: "/var/www/vhosts/{{ ansible_hostname }}"

- name: template vhosts file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd

