---
- name: use vhost role playbook
  hosts: webservers

  pre_tasks:
    - debug:
        msg: 'begining web server configuration'

  roles:
    - myvhost

  post_tasks:
    - debug:
        msg: 'Web server has been configured.'



